### ISSUE TITLE
tilemaker format status

### ISSUE THREAD

**Issue by Alphatiger** [systemed/tilemaker#10]
Is there any way we can host tilemaker output .pbf files,

I tried to host in apache and used leaflet vector plugin started getting unimplemented error.

If there is any other way or some help, kindly advise.

**Comment by systemed** [comment]
I've successfully got the Leaflet.MapboxVectorTile plugin reading tiles. Do you have a link to your tiles anywhere to test against?

**Comment by Alphatiger** [comment]
http://ec2-52-3-48-243.compute-1.amazonaws.com/rhode/
I have hosted them for preusal, data is rhodeisland taken from http://download.geofabrik.de/north-america/us/rhode-island-latest.osm.pbf, after using tilemaker they are hosted in apache (strictly apache no other modules)

**Comment by systemed** [comment]
I think this is because the .pbfs are compressed (standard zlib deflate) and Leaflet.MapboxVectorTile doesn't know how to uncompress them.

If you set `"compress"` to `false` in the config file, it'll create uncompressed tiles which Leaflet.MapboxVectorTile can read. Alternatively, you can tell Apache to send a `Content-Encoding: gzip` header with each file, perhaps simply with an .htaccess directive like this:

`Header set Content-Encoding: gzip`

The spec for vector tile compression is [a bit of a mess](https://github.com/mapbox/vector-tile-spec/issues/27) and Tilemaker tries to just do whatever you tell it!

**Comment by pnorman** [comment]
> Alternatively, you can tell Apache to send a Content-Encoding: gzip header with each file

Yes, this is the preferred method. To do it right, it also needs to reject requests that only accept identity. You SHOULD NOT serve the file as compressed if no Accept-Encoding header was sent, but I believe Mapbox studio is broken and fails to send accept-encoding, so you may need to ignore the HTTP RFC SHOULD.

**Comment by pnorman** [comment]
nginx might be easier, with the [ngx_http_gzip_static_module](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html#gzip_static) and the "always" value. Haven't tried it myself.

**Comment by Alphatiger** [comment]
thank you guys, it is working now compress=false, i haven't tried the server solution, will try it soon

**Comment by systemed** [comment]
Great - glad it's working.

**Comment by Booligoosh** [comment]
Just an fyi for anyone coming across this now, rather than `"compress": false` you want `"compress": "none"`
