### ISSUE TITLE
std::bad_alloc during tilemaker with docker

### ISSUE THREAD

**Issue by silgon** [systemed/tilemaker#122]
I built the docker image as described in the readme `docker build . -t tilemaker` and then I applied the command as also specified. Here is my output:

```bash
$ docker run -v $PWD:/srv -i -t --rm tilemaker /srv/planet-latest.osm.pbf --output=/srv/planet.mbtiles
Layer waterway (z11-14)
Layer transportation (z12-14)
Layer building (z14-14)
Layer poi (z13-14)
Reading /srv/planet-latest.osm.pbf
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
````
Do you have an idea of the possible cause of this problem. The `pbf` file has been downloaded with `wget https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf`.

Thanks in advance.

**Comment by systemed** [comment]
This is probably just running out of memory. Tilemaker isn't designed to be able to process the whole planet - it's theoretically possible but you'd need many, many gigabytes of RAM. It's intended for regional/city extracts. There are other vector tile solutions available which load the .osm.pbf into a database first so that it doesn't have to be memory-resident.

**Comment by silgon** [comment]
It seems to be exactly that. My computer has 24Gb of ram and it takes all the ram, then the swap and then it fails. I was just curious to know of it was able to do run it with `docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`, which works with the  `mbtiles` file. In that case, I'll ask the general question of: how do you deploy a planet server?

**Comment by systemed** [comment]
Generally you'll want to read the .osm.pbf into a Postgres/PostGIS database, then run a vector tile server that receives tile requests, gets the corresponding data from the database, and sends it back in vector tile form. There are a couple of options for this: OpenMapTiles offers a reasonably off-the-shelf way of doing it, while Tegola is an excellent option if you want a bit more control. Have a look at https://github.com/mapbox/awesome-vector-tiles and http://www.paulnorman.ca/blog/2016/11/serving-vector-tiles/ .

**Comment by skylarmt** [comment]
What kind of RAM:osm.pbf ratio are we talking about?  I got this error on a 8GB osm.pbf file, and my system has 32GB of RAM, plus another 32GB of swap space.

I'd rather use up my $20 SSD and have tilemaker take a week or more to run, than simply crash without $100+ of additional RAM.  Other memory-intensive programs don't stop using RAM until the kernel's oom-killer kicks in because the system is about to crash.  That's what I want.
