### ISSUE TITLE
Add function to get current tile lat/lon

### ISSUE THREAD

**Issue by michalfratczak** [systemed/tilemaker#167]
Recently introduced function way:MinZoom() allows to discard polygons that are small relative to current tile area.
The easiest way is to take ratio _way:Area()/current_tile_area_ and discard smaller than 1%

current_tile_area can be approximately calculated with [this](https://wiki.openstreetmap.org/wiki/Zoom_levels), but it's dependant on tile latitude. 

Can we have a function to get current tile center lat/lon ? Or maybe current "way" center lat/lon ?

**Comment by systemed** [comment]
Good idea!

Tile lat/lon isn't really practical - we only call `way_function` once per object, not at every zoom level.

Way lat/lon is pretty easy for linear features and simple areas, but we can't currently do it for multipolygons. That's because we read nodes first, then relations, then ways - so we don't yet have the way members when we call `way_function` for a multipolygon relation, and without that, we can't calculate the centroid.

I'd like to fix this (it's the same reason that `:Intersects` and `:FindIntersecting` don't work on multipolygons) but am not sure yet how best to do so...

**Comment by ogre** [comment]
Thanks
For me it's not a high priority feature, just a neat idea.
When creating tiles for a medium sized country/city (not world/continent), the tile latitude can be hardcoded and won't introduce big error for purpose of setting MinZoom.
