### ISSUE TITLE
Filter out ways when importing

### ISSUE THREAD

**Issue by ttsirkia** [systemed/tilemaker#190]
If I have understood correctly, while reading the pbf file `tilemaker` will store all the ways to the memory. Based on the number of ways to be found, the memory consumption can be high.

What if I needed only, let's say motorways or land usage information, would it be possible to have some kind of filter Lua function to skip those ways which are not relevant? Does it already work like that for nodes with the `node_keys` list?

I think this would reduce the memory consumption quite a lot if the whole information is not needed but are there some drawbacks or something that I didn't understood correctly about the import process?

**Comment by ttsirkia** [comment]
OK. I made some experiments with Estonian map data as it is not a tiny but not too big.

With the shipped OSM process files:
`Stored 10045947 nodes, 1165834 ways, 3396 relations`

With the shipped almost blank process files:
`Stored 10045947 nodes, 1092984 ways, 303 relations`

With an empty process file which does not include anything:
`Stored 10045947 nodes, 84422 ways, 0 relations`

So the node number is always the same but ways seem to reduce. However, it is not zero in the last test. The `.osm.pbf` file is 83 MB, the memory consumption in the first two tests around 1 GB and in the last around 500 MB. Is there actually anything that could be reduced in the importing phase to drop out unnecessary data prior writing the `mbtiles` file?

**Comment by systemed** [comment]
Yes, tilemaker reads all nodes in the .pbf first, then (multipolygon) relations, then ways. It needs to read nodes before ways so that, when processing a way, it has the location of the way available for functions like `way:Intersects` (and I'd like to add more functions like this, as per #167).

`node_keys` is just a speed optimisation that avoids calling the Lua code for uninteresting nodes - it doesn't affect memory usage.

I suspect the reason that the OMT and example process files have similar results is because both of them include buildings, which are the biggest contributor to OSM data bloat.

You can eliminate unwanted nodes from the .pbf in advance by using tools such as osmfilter/osmconvert or osmium. You can also potentially reduce memory requirements by preprocessing the .pbf using [mapsplit](https://github.com/simonpoole/mapsplit).

_Conceivably_ we could implement a `way_keys` function that did an extra first pass to read ways, and if they match the tags, note their waynodes. Only then would we then read the node lat/lon on the next pass. That's not something I have any plan to implement (osmfilter/osmconvert does the same and works for me) but I wouldn't reject a PR implementing it.

Another possibility I've considered is adding a runtime switch that states all nodes in the .pbf are consecutively numbered (i.e. 1,2,3,4... without any gaps). You can produce .pbfs like this with `osmium renumber`. This would allow us to use a vector (array) rather than a sparse_map (hash) for node storage, which would lead to a useful memory saving.

**Comment by ttsirkia** [comment]
Thanks for the very detailed answer! I'll take a look at these options.

**Comment by ttsirkia** [comment]
Osmium seems to be the easiest option as it can read and write directly `.osm.pbf` files, https://osmcode.org/osmium-tool/manual.html#filtering-by-tags
