### ISSUE TITLE
Shape breaks at a certain distance

### ISSUE THREAD

**Issue by toshelp** [systemed/tilemaker#215]
When I generated mbtiles with a tilemaker, I found that the shape was broken. However, not found if it was generated by Openmaptiles. (I used the same data source for the generation.)
This seems to occur every about 0.013682 latitudes.

Generated by tilemaker (coordinates: 19.63/51.4813694/-0.0254236)
![tilemaker_break_](https://user-images.githubusercontent.com/72679776/113303580-30253e00-933c-11eb-8114-221ca401e8ce.png)

Generated by Openmaptiles
![openmaptiles_](https://user-images.githubusercontent.com/72679776/113303645-416e4a80-933c-11eb-8a40-18912b898493.png)

**Comment by kleunen** [comment]
Is it an artifact from the clipping? Each tile clips the line, but due to the fact different clipping rectangles are used, the partial lines result in diffferent coordinates?

**Comment by kleunen** [comment]
Can you try #218 ?

**Comment by kleunen** [comment]
![image](https://user-images.githubusercontent.com/230050/113562683-d4420a00-9606-11eb-9d34-b92d2cec56a9.png)

I think the line does still look a bit broken

**Comment by kleunen** [comment]
It does result in problems when rendering:
![image](https://user-images.githubusercontent.com/230050/113571905-7e299280-9617-11eb-977e-6eb438f7b95f.png)

**Comment by toshelp** [comment]
I tried #218 and got the same result as you. I could understand that it was due to rounding.
Thank you for explanation.

**Comment by kleunen** [comment]
It does result in problems in the output. I think this is a real issue.

**Comment by kleunen** [comment]
This is really an odd bug, I had a look into it. But I don't understand. I tried removing the margin from the clippingbox, than the weird Z jump in the line is done. But there is a small gap. I also tried removing the clipping in output_object.cpp:

````
        case OutputGeometryType::LINESTRING:
        {
            MultiLinestring out;
            //geom::intersection(osmStore.retrieve<mmap::linestring_t>(oo.handle), bbox.clippingBox, out);
            geom::assign(out, osmStore.retrieve<mmap::linestring_t>(oo.handle));
            return out;
        }
````

But when doing so, the line is still incorrect. This is really something @systemed should look at. Maybe some clipping is going on at some other place as well ?

**Comment by kleunen** [comment]
@systemed I had the idea to cut up the linestring into sections that overlap the tile. But this does not help. Like so
````
        case OutputGeometryType::LINESTRING:
        {
            mmap::linestring_t const &ls = osmStore.retrieve<mmap::linestring_t>(oo.handle);
            MultiLinestring out;
            Linestring current_ls;

            geom::for_each_point(ls, [&](mmap::point_t const &p) {
                if(geom::within(p, bbox.clippingBox)) {
                    geom::append(current_ls, p);
                 } else {
                    if(!current_ls.empty()) {
                        if(!geom::within(current_ls.back(), bbox.clippingBox)) {
                            if(current_ls.size() > 1)
                                out.push_back(std::move(current_ls));
                            geom::clear(current_ls);
                        }
                    }
                    geom::append(current_ls, p);
                }
            });

            if(current_ls.size() > 1)
                out.push_back(std::move(current_ls));

            //geom::intersection(osmStore.retrieve<mmap::linestring_t>(oo.handle), bbox.clippingBox, out); */
            return out;
        }

**Comment by systemed** [comment]
I'll take a look. There's some sort of rounding issue but we might need a test case to determine whether it's within tilemaker (as per #218) or boost::geometry. Suspect this isn't going to be an easy one to iron out but I agree, it would be worth fixing.

**Comment by kleunen** [comment]
Yes, I am starting to suspect boost::geometry. I am thinking maybe the linestring gets broken into a multilinestring when reading. I looked at the input pbf within josm, and indeed, the input geometry is fine and a single linestring. But when you look at the output, you can see that it is split up into multiple linestrings. Removing the clipping from output_object.cpp seems to make no difference, so i don't think it is the clipping.

**Comment by systemed** [comment]
There's apparently a BOOST_GEOMETRY_NO_ROBUSTNESS macro; if it's not defined (i.e. default) then some internal rescaling to integer happens. I haven't been able to identify a visible difference with it defined, though I'm building this with Boost 1.69 and things may have changed with later versions.

**Comment by systemed** [comment]
https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165 makes this a little bit better but the issue's still there.

You can make it still better by changing the buffer size in coordinates.cpp:

    xmargin = (maxLon -minLon )/200.0;
    ymargin = (maxLatp-minLatp)/200.0;

Change the 200.0 to (say) 16.0 and that reduces it further, at the cost of larger filesize. This is usually known as the "[tile buffer](https://blog.cyclemap.link/2020-01-25-tilebuffer/)". I'll add an option to make this configurable per zoom level in the future.

But even then it's not completely resolved. As above I think we're encountering an accuracy issue with boost::geometry::intersection.

In theory we actually need something simpler - if there's a polyline ABC|DE, where ABC are outside the enlarged tile boundary (|) and DE are within it, then CDE would do us fine. bg::intersection gives us |DE, and calculating the intersection point at | seems to be where the issue is. But that's not an option available to us.

Next step is probably working up a simple reproducible single-file test case and seeing if we can pin down the issue.

**Comment by kleunen** [comment]
It might be possible that boost intersection is fine. But when you later store the coordinates to the database, the coordinates get rounded when converting to an integer.

Also it is fine if ABC if C is outside the normal tile boundaries. because the adjacent tile will store BCD and the section BC will overlap.

**Comment by kleunen** [comment]
Ah ok. The rounding is what you have fixed :)

**Comment by systemed** [comment]
Well, "made slightly less bad" rather than "fixed" :) . It's still likely that the point outside the tile isn't being recorded 100% accurately (because of rounding). Increasing the buffer size will often fix this, because it means we're more likely to include the real co-ordinate of the next polyline vertex rather than our interpolation. But if the segment is long then we'll still get an interpolated vertex, so we want to avoid that whenever possible.

Essentially in a scenario like this:

![clipping](https://user-images.githubusercontent.com/694425/116232300-dacd2880-a751-11eb-846a-23b006ba3885.png)

we're currently introducing new vertices at the stars, which may be inaccurate due to rounding. What we want to do is keep the whole segment as far as the next vertex - in other words, keep all the blue segments but remove the red ones.

I think we could write our own clipping routine for polylines, but I don't particularly fancy doing it for multipolygons, especially given issues around winding order and the like!

**Comment by kleunen** [comment]
Yes the following code, was my attempt to replace the clipping, by splitting the linestring into multiple linestrings. And only keeping the line sections which overlap with the tile: 

````C++
case OutputGeometryType::LINESTRING:
        {
            mmap::linestring_t const &ls = osmStore.retrieve<mmap::linestring_t>(oo.handle);
            MultiLinestring out;
            Linestring current_ls;

            geom::for_each_point(ls, [&](mmap::point_t const &p) {
                if(geom::within(p, bbox.clippingBox)) {
                    geom::append(current_ls, p);
                 } else {
                    if(!current_ls.empty()) {
                        if(!geom::within(current_ls.back(), bbox.clippingBox)) {
                            if(current_ls.size() > 1)
                                out.push_back(std::move(current_ls));
                            geom::clear(current_ls);
                        }
                    }
                    geom::append(current_ls, p);
                }
            });

            if(current_ls.size() > 1)
                out.push_back(std::move(current_ls));

            //geom::intersection(osmStore.retrieve<mmap::linestring_t>(oo.handle), bbox.clippingBox, out); */
            return out;
        }
````

But I say no improvement, maybe i was missing something. My theory was, that because you are not splitting the line and not calculating new points, you will get rounding errors, but they are consistent. Say linesection BC is part of two tiles, they both store the same begint and end point. And both these same points are rounded in the same way. So there is a rounding error, but you should not be able to see it. At least, that was my theory ...

For multipolygons, i think they are almost always filled ? So you won't notice the errors that much. Ideally you would clip them at existing points on the polygon. But the outer should still go around the inner polygons. So, that is not easy i guess.

**Comment by kleunen** [comment]
Have a look at #234

**Comment by kleunen** [comment]
@toshelp Can you verify the current master resolves your issue now ? 
The approach changed a bit, but I think the issue is now resolved.

**Comment by toshelp** [comment]
#234 (https://github.com/systemed/tilemaker/commit/12b34febc71df71da26529a58f48bbd750c7c194) worked fine!
Output is very impressive.

This issue is resolved.
Thank you!
