### ISSUE TITLE
--skip-integrity is broken after new year commits

### ISSUE THREAD

**Issue by Silvercast** [systemed/tilemaker#358]
Hi,
First of all I really appreciate your awesome work. What I found is the conversion from pbf to mbtiles is broken with `--skip-integrity`. I have some edge cases where I have to deal with pbf files with non-perfect integrity and rely on `--skip-integrity` to finish my pipeline. It used to work on commit 27b3a7bc5eef1aeeed663c061c0cdcedb62099e5 but not after that.

If there is a better way to process pbf files before converting to mbtiles I'm happy to learn.

**Comment by systemed** [comment]
Could you upload the problematic .pbf somewhere so I can take a look?

**Comment by Silvercast** [comment]
Absolutely, please check the file. FYO I compiled using Docker image to make sure the environment is clean.

[output.pbf.zip](https://github.com/systemed/tilemaker/files/7803434/output.pbf.zip)

**Comment by systemed** [comment]
`--skip-integrity` only deals with missing nodes from ways, not missing ways from multipolygon relations.

What you have here, I think, is a way missing from a multipolygon relation. This is always problematic because tilemaker can't make a valid geometry from it. You can check the integrity of an extract using osmium:

    galibier:tilemaker richard$ osmium check-refs -r ~/Maps/planet/broken.osm.pbf 
    [======================================================================] 100% 
    There are 1044704 nodes, 116245 ways, and 2187 relations in this file.
    Nodes     in ways      missing: 31775
    Nodes     in relations missing: 758
    Ways      in relations missing: 15777
    Relations in relations missing: 393

As far as I can tell, https://github.com/systemed/tilemaker/commit/eb2607dcd6b6e2473187947235f8b3c8aada6cbe has accidentally triggered this because it's now (correctly) reading in some data that wasn't processed before, and that data happens to be problematic.

If you're generating your .pbf extracts with osmium then using `strategy=smart` will automatically do the right thing (see #324). With Osmosis I think `clipIncompleteEntities=true` will do the job. (See #324, #125.)

**Comment by Silvercast** [comment]
you're right, the pbf file contains missing ways. Filtering them out in preprocessing is a much preferable way. `clipIncompleteEntities` solves the issue 👍 Thanks for your support.
