### ISSUE TITLE
Last tile thread takes forever to render?

### ISSUE THREAD

**Issue by billysan** [systemed/tilemaker#373]
Talking big scale (europe) *.pbf inputs.

Running with --compact.

I'm not claiming this is an issue but would love to understand the under-the-hood mechanics that lead to this happening.

It would be awesome to have an "unlock" option to be able to signal tilemaker to stop processing all remaining threads and write the database gracefully with metadata.

**Comment by systemed** [comment]
> I'm not claiming this is an issue but would love to understand the under-the-hood mechanics that lead to this happening.

Essentially I think it's when tilemaker gets stuck on a big, complex geometry that is very time-consuming to simplify or correct. People have a habit of making ludicrously complex multipolygons for lakes, estuaries, forests and the like. All the other geometries are processed successfully while tilemaker is still grinding away on this complex one. I would like to put some logging in, so that we could potentially find exactly which objects are causing slow processing, and try to optimise it.

**Comment by billysan** [comment]
That sounds great.

How hard it will be to listen to a custom signal to abort rendering and proceed to writing the metadata and flushing the database to disk?

**Comment by systemed** [comment]
It would be plausible to listen for (say) SIGTSTP in `ProcessObjects` in tile_worker.cpp, and stop processing the current object if received. Not something I have any experience in but doable I presume!

**Comment by systemed** [comment]
#387 should also make a big difference to the "one tile taking ages to render" issue.

**Comment by billysan** [comment]
Great stuff!
