### ISSUE TITLE
Weird extra ocean shape

### ISSUE THREAD

**Issue by timsluis** [systemed/tilemaker#398]
Tilemaker is truly awesome, thanks!

When creating tiles for The Netherlands, an extra polygon appears party outside the bbox. See:
<img width="717" alt="Screenshot 2022-03-21 at 11 29 07" src="https://user-images.githubusercontent.com/235880/159243760-8492053d-f4d4-453b-b982-5b48046f6bd5.png">
 
It is also included in the tiles when I don't include ocean tiles, so it appears to be related to the water group.

Any idea where it might be coming from?

**Comment by systemed** [comment]
Someone has helpfully™ created an area in OSM for the German Bight: https://www.openstreetmap.org/relation/13915560

It's not really settled how OSM deals with these sort of polygons. Ideally there'd be some sort of tag to say "this entirely overlaps the ocean" so that tilemaker could ignore it.

If you want a quick fix then you could just hardcode an override into process-openmaptiles.lua somewhere around line 480:

    if natural=="bay" and way:Find("wikidata")=="Q321837" then return end

**Comment by timsluis** [comment]
Thanks! Will apply the quick fix first then.

OSM related question: I looked for the polygon in OSM to see what is was, but couldn't find it. How did you select the shape in OSM?

**Comment by systemed** [comment]
I used the "Query features" tool on osm.org and looked for it in "Enclosing features"!

I've just added `ocean=yes` (which has some prior use) to the OSM relation which will allow us to automatically filter it out in future.

**Comment by dieterdreist** [comment]
a natural=bay should not trigger water rendering, it must be contained within the sea area defined by natural=coastline
this is what the wiki says

https://wiki.openstreetmap.org/wiki/Tag:natural%3Dbay

“ This tag is for marking named bays. Note that this tag is not for tagging presence of water, this is done using natural=water, natural=coastline (and also waterway=riverbank, landuse=reservoir). Parts of area with natural=bay area may be land - for example islands may be considered as being a part of bay and mapped this way.”

**Comment by timsluis** [comment]
So in process-openmaptiles.lua line477:
`if natural=="water" or natural=="bay" or leisure=="swimming_pool" or landuse=="reservoir" or landuse=="basin" or waterClasses[waterway] then` natural=="bay" should be removed?

**Comment by systemed** [comment]
> this is what the wiki says

The problem is that what the wiki says and what's encountered in the wild are not necessarily the same thing :)

**Comment by dieterdreist** [comment]
yes, but if we decide to go with the current settings we will produce wrong results for mapping that is according to the docs (like in this very issue), just because we think there might be cases which are in contratiction, and we want to support them?
Thinking from a political pov about which interpretation should be supported (is maybe out of scope here), the wiki interpretation seems to make more sense (see islands as part of a bay, if they are within).

**Comment by systemed** [comment]
It would be really lovely if someone were to consistently fix up the bad data and tell the offenders to mend their ways, yes.
