### ISSUE TITLE
lua runtime error: ../resources/process-openmaptiles.lua:123: attempt to call global 'Find' (a nil value)

### ISSUE THREAD

**Issue by StephenAtty** [systemed/tilemaker#652]
Using the precompiled V3.0 ubuntu binaries.
```
Reading .pbf ../data/ireland-and-northern-ireland-latest.osm.pbf
lua runtime error: ../resources/process-openmaptiles.lua:123: attempt to call global 'Find' (a nil value)
lua runtime error: lua runtime error: ../resources/process-openmaptiles.lua:123: attempt to call global 'Find' (a nil value)
lua runtime error: ../resources/process-openmaptiles.lua:123: attempt to call global 'Find' (a nil value)
lua runtime error: ../resources/process-openmaptiles.lua:123: attempt to call global 'Find' (a nil value)
terminate called recursively

```

line 123 is

	local aeroway = Find("aeroway")

Code runs fine for mainland UK

**Comment by systemed** [comment]
I don't have a 22.04 installation to test the binary on I'm afraid, but it works fine with that extract from source on 20.04.

Are you sure you're running the downloaded tilemaker binary (i.e. `chmod +x build/tilemaker ; ./build/tilemaker ../data/ireland` etc.) rather than using your previously installed one? The error is consistent with what would happen if you tried to run tilemaker 2.x on a tilemaker 3.0 Lua script.

**Comment by StephenAtty** [comment]
You are quite right - not sure why I didn't notice that myself - I'd put the precompiled binary in the working directory but not updated the script I was running it from
