### ISSUE TITLE
Handling large river relations

### ISSUE THREAD

**Issue by TimSC** [systemed/tilemaker#87]
Large rivers are sometimes tagged as a series of start-to-end connected ways (tagged natural=water and water=river) within a relation. Example: https://api.openstreetmap.org/api/0.6/relation/1775822/full The overall shape forms a loop but there is no guarantee that a particular extract will have the complete loop. Some options:

* Extract and find complete polygons in a proprocessing step, then save to a shape file. This approach is used for coastlines. #16 Unfortunately, most coastline extracts do not contain riverbank data?
* Try to process river sections in tilemaker, and infer any missing sections (quite hard)
* Change all instances of this mapping style to closed ways (unpopular)

Are there any other large shapes that use similar tagging? I've occasionally seen natural=wood like this but I tend to edit the map to be closed ways. (boundary=national_park?)

Any thoughts @systemed ?

**Comment by systemed** [comment]
I suspect you're right in that inferring missing sections is too hard and changing the mapping style impossible, so that pretty much leaves option 1.

I wonder if it's possible to do this out of the box with ogr2ogr, by creating an `osmconf.ini` file that looks for that tagging combination, then reading the .pbf and outputs it as a shapefile. In theory it looks possible but I've not tried it.

**Comment by pnorman** [comment]
> Are there any other large shapes that use similar tagging?

This really isn't about rivers, but is about all multipolygons. Geofabrik extracts now contain all children of a relation when that relation is a multipolygon and part of it is in the extract.
